### ISSUE TITLE
Incorrect execution order for raf

### ISSUE THREAD

**Issue by Sv1nnet** [vault-developer/event-loop-explorer#28] opened 2024-12-11 19:14 UTC
Hi! I noticed that nested callbacks in requestAnimationFrame is called during one render, but should be called on every next render for every nested callback
```js
requestAnimationFrame(() => {
    console.log(1)
    queueMicrotask(() => console.log(2));  
    
    requestAnimationFrame(() => {
        console.log(3)
        queueMicrotask(() => console.log(4));  
        
        requestAnimationFrame(() => {
            console.log(5)
        });
        
        queueMicrotask(() => console.log(6));  
        console.log(7)
    });
    
    queueMicrotask(() => console.log(8));  
    console.log(9);
});
```
<img width="49" alt="Screenshot 2024-12-11 at 22 12 15" src="https://github.com/user-attachments/assets/d9a4ba4d-2ca3-466c-ab67-ff6419a9af86" /> this is in chrome

![Screenshot 2024-12-11 at 22 13 13](https://github.com/user-attachments/assets/699df96c-6e89-442b-84db-d299aee55ede) this is in your app

**Comment by vault-developer** [comment] 2024-12-29 20:13
Hey @Sv1nnet, thank you for raising the issue!
I can confirm that the order was incorrect.
The problem is fixed now 👍

**Closed** 2024-12-29 20:12 UTC
